name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # strategy set
    strategy:
      matrix:
        go: [ '1.17','1.18','1.19','1.20' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Test
        run: go test -v -race ./...